### ISSUE TITLE
where's the View obv?

### ISSUE THREAD

**Issue by mixmix** [flumedb/flumedb#15]
README: 

> The trick is that each view exposes an observable that represents it's current state. An observable is like an event meets a value. it's an changing value that you can observe. Events, promises, or streams are similar, but not quite the right choice here.

I was promised an observeable. I can't see how to access it (code nor docs)
EITHER - provide `db[viewName].obs`
OR - can we clarify what is meant by that paragraph :)

**Comment by mixmix** [comment]
oh it's `db[viewName].value`
I'll have a think about where to put that in the docs

**Comment by dominictarr** [comment]
Oh no, it's `[viewName].since` the log also has a `since`... since being the sequence number of the latest message processed. `[viewName].value` is a flumeview-reduce feature. flumeview-level doesn't have that.

**Comment by mixmix** [comment]
I imagined I would be intersted in using the obv of the viewState ... the
sequence as an obv doesn't seem useful?
If it isn't that useful I would
EITHER remove the talk about obv being exposed (which sent me looking),
OR mention the obv that's in there (value) as part of the api

I'm aware I'm poking the READMEs without having built a lot of things with
this stuff yet. I am doing this because I want others to find it clear
where I have not. For the most part it's been pretty clear, but figure we
should do this now, because coming back to it and seeing things fresh is
hard. Trust you'll tell me if I'm off with my feel for the use of things.

**Comment by nichoth** [comment]
Maybe a little change would make it clearer, something like

> The trick is that each view exposes an [observable](https://github.com/dominictarr/obv), `flumeview.since`, that represents it's current state — the sequence of the last value processed by the view. An observable is like an event meets a value. it's an changing value that you can observe. Events, promises, or streams are similar, but not quite the right choice here.

**Comment by dominictarr** [comment]
I've edited this basically @nichoth's text... not a close reading: each view exposes an observable that _represents_ it's current state. The observable in question _represents_ the state, but it isn't the state.  But that is too implicit to be useful.

@mixmix this is all really valuable feedback! it's really useful to see you processing this with beginner's eyes. please post more issues!

**Comment by dominictarr** [comment]
fixed in 0.4.5

**Comment by mixmix** [comment]
Your edit mentioning sequence is good. Nice wording nichoth!

Having to write beginners guides is also a good push on what minimal
examples look like too I've found.
I'm learning a lot too

**Comment by christianbundy** [comment]
I think this is resolved and ready to close, please re-open if not!
