### ISSUE TITLE
Question: is log truncation supported?

### ISSUE THREAD

**Issue by juancampa** [flumedb/flumedb#21]
Hey, I've been playing with flume and now I'm thinking about the idea of truncating the log if it gets too big.  If the log is only accessed through views, and I'm not expecting views to change versions ever, it should be possible to delete old log entries.

Is this something that flumedb currently supports? Has anyone already implemented this?

Thanks!

**Comment by dominictarr** [comment]
On the file system you can truncate files, but on flume this would mean deleting the most recent records! (surely you want to delete the old records)
you could copy the log to a new log that didn't have the old messages in it, but then you'd have to rebuild the views. if you use flumeview-level or flumeview-hashtable, those views are pointers into the log, so they wouldn't work if the old messages the pointed to weren't there.

hmm: if you had another log implementation that only created a file of a fixed size, say 10 or 100 mb, then started another file (so the log is split across many files) then you could just delete the old one, you couldn't access those old messages.

probably a more practical way to save space is to be more restrained in the views you create. (at least in the our use case of secure-scuttlebutt about half the flume disk usage is views, and half is log)

**Comment by juancampa** [comment]
Yeah. Definitely old messages.

I like the multiple files idea, seems simple enough. I don't need this right now but just making sure this idea is not completely insane and can be implemented in the future if needed.

Thanks for sharing your thoughts!

**Comment by juancampa** [comment]
Also, I'll take a look at the ssb code to get an idea of what kinds of views you guys have. Thanks for pointing that out, there's probably a lot to learn there
