### ISSUE TITLE
Get list of flumeviews used?

### ISSUE THREAD

**Issue by christianbundy** [flumedb/flumedb#25]
I don't know whether this would be helpful for others, or if it's just specific to me because I'm monkey-patching together a `flumedb.del()` prototype, but is it possible to get a list of views in use? It might be helpful to export an interface to [`flumedb.views`](https://github.com/flumedb/flumedb/blob/2459b08c5894504f779f79f9b425ed22ba32a3e9/index.js#L34), but again, this might be hyper-specific to playing around with flumedb rather than actually using it in production.

**Comment by dominictarr** [comment]
would merge.
